image: docker:git

stages:
  - build
  - test
  - deploy

variables:
  IP: 195.201.39.96
  REGISTRY_DOMAIN: registry.thiloilg.com
  APP_NAME: app
  API_NAME: api

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  stage: build
  script:
    - docker build -t $APP_NAME ./$APP_NAME
    - docker build -t $API_NAME ./$API_NAME
    - docker tag $APP_NAME $REGISTRY_DOMAIN/repo/blicc/$APP_NAME
    - docker tag $API_NAME $REGISTRY_DOMAIN/repo/blicc/$API_NAME

test:
  stage: test
  script:
    - echo "Testing" # TODO: yarn test in docker containers

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push $REGISTRY_DOMAIN/repo/blicc/$APP_NAME
    - docker push $REGISTRY_DOMAIN/repo/blicc/$API_NAME
    - scp -r ./docker-compose.yml root@$IP:/root/
    - ssh -tt root@$IP "docker-compose pull"
    - ssh -tt root@$IP "docker-compose -f /root/docker-compose.yml up -d --force-recreate"
