

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t blicc-api ./api

test:
  stage: test
  script:
    - echo "Testing"

deploy:
  stage: deploy
  script:
    - docker push registry.thiloilg.com/repo/blicc/blicc-api
    