stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t blicc-api ./api
    - docker tag blicc-api registry.thiloilg.com/repo/blicc/blicc-api
test:
  stage: test
  script:
    - echo "Testing" # TODO: yarn test in docker containers

deploy:
  stage: deploy
  script:
    - docker push registry.thiloilg.com/repo/blicc/blicc-api
