stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  stage: build
  script:
    - docker build -t blicc-api ./api
    - docker tag blicc-api registry.thiloilg.com/repo/blicc/blicc-api
test:
  stage: test
  script:
    - echo "Testing" # TODO: yarn test in docker containers

deploy:
  stage: deploy
  script:
    - docker push registry.thiloilg.com/repo/blicc/blicc-api
    - ssh -tt root@195.201.39.96 "docker-compose -f /root/docker-compose.yml up -d --force-recreate"
