image: ubuntu:18.04

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - apt-get install -qq curl
  - curl -sSL https://get.docker.com/ 54 | sh
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  stage: build
  script:
    - docker build -t blicc-api ./api
    - docker tag blicc-api registry.thiloilg.com/repo/blicc/blicc-api
test:
  stage: test
  script:
    - echo "Testing" # TODO: yarn test in docker containers

deploy:
  stage: deploy
  script:
    - docker push registry.thiloilg.com/repo/blicc/blicc-api
    - ssh -tt root@195.201.39.96 "docker-compose -f /root/docker-compose.yml up -d --force-recreate"
