stages:
  - build
  - test-preparation
  - test
  - deploy
  - seed

variables:
  REPO: blicc
  USER: root

.enable_ssh: &enable_ssh |
  which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.login_docker: &login_docker |
  echo "$CI_REGISTRY"
  echo "$CI_REGISTRY_USER"
  docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.install_openssl: &install_openssl |
  apk add --update openssl
  rm -rf /var/cache/apk/*

build:
  stage: build
  image: docker:git
  before_script:
    - *login_docker
  script:
    - docker build -t app -f ./app/prod.Dockerfile ./app
    - docker build --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD -t api -f ./api/prod.Dockerfile ./api
    - docker build --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD -t db ./db
    - docker build --build-arg MONGODB_PASSWORD=$MONGODB_PASSWORD -t mongo ./mongo
    - docker build --build-arg MONGODB_PASSWORD=$MONGODB_PASSWORD -t delivery -f ./delivery/prod.Dockerfile ./delivery
    - docker build -t redis ./redis
    - docker build -t mock-api -f ./mock-api/prod.Dockerfile ./mock-api

    ## tag for testing stage
    - docker tag api $REGISTRY_DOMAIN/$USER/$REPO/api-testing-stage
    - docker tag db $REGISTRY_DOMAIN/$USER/$REPO/db-testing-stage
    - docker tag redis $REGISTRY_DOMAIN/$USER/$REPO/redis-testing-stage
    - docker tag mongo $REGISTRY_DOMAIN/$USER/$REPO/mongo-testing-stage
    - docker tag mock-api $REGISTRY_DOMAIN/$USER/$REPO/mock-api-testing-stage
    - docker tag delivery $REGISTRY_DOMAIN/$USER/$REPO/delivery-testing-stage

    ## tag for production
    - docker tag api $REGISTRY_DOMAIN/$USER/$REPO/api
    - docker tag db $REGISTRY_DOMAIN/$USER/$REPO/db
    - docker tag mongo $REGISTRY_DOMAIN/$USER/$REPO/mongo
    - docker tag redis $REGISTRY_DOMAIN/$USER/$REPO/redis
    - docker tag app $REGISTRY_DOMAIN/$USER/$REPO/app
    - docker tag delivery $REGISTRY_DOMAIN/$USER/$REPO/delivery

    ## push for testing stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/api-testing-stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/db-testing-stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/redis-testing-stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/mongo-testing-stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/mock-api-testing-stage
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/delivery-testing-stage

test-preparation:
  stage: test-preparation
  image: node:12
  before_script:
    - *enable_ssh
  script:
    - ssh -tt root@$TEST_IP "docker image prune -a -f"
    - scp -r ./docker-compose.testing-stage.yml root@$TEST_IP:/root/docker-compose.yml
    - ssh -tt root@$TEST_IP "export
      DOCKER_CLIENT_TIMEOUT=120
      COMPOSE_HTTP_TIMEOUT=120
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      CI_REGISTRY=$CI_REGISTRY
      CI_REGISTRY_USER=$CI_REGISTRY_USER
      CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD
      ADMIN_MAIL=$ADMIN_MAIL
      ADMIN_PASSWORD=$ADMIN_PASSWORD
      MAIL_ADDRESS=$MAIL_ADDRESS
      MAIL_PASSWORD=$MAIL_PASSWORD
      MAIL_HOST=$MAIL_HOST &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker-compose pull &&
      docker-compose down &&
      docker-compose up -d --force-recreate --remove-orphans"
    - for ((;;)); do curl -s $API_TEST_TARGET > /dev/null && break; sleep 1; done
    - for ((;;)); do curl -s $DELIVERY_TEST_TARGET > /dev/null && break; sleep 1; done

test-api:
  stage: test
  image: node:12
  script:
    - yarn
    - yarn --cwd 'api' cross-env API_TEST_TARGET=$API_TEST_TARGET jest

test-delivery:
  stage: test
  image: golang:1.13
  script:
    - cd delivery && go test ./pkg/channel/...

deploy:
  stage: deploy
  image: docker:git
  only:
    - master
  before_script:
    - *login_docker
    - *enable_ssh
    - *install_openssl
  script:
    - ssh -tt root@$PROD_IP "docker image prune -a -f"
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/app
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/api
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/db
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/mongo
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/redis
    - docker push $REGISTRY_DOMAIN/$USER/$REPO/delivery
    - scp -r ./docker-compose.prod.yml root@$PROD_IP:/root/docker-compose.yml
    - openssl genrsa -out rsa.pem 2048
    - openssl rsa -in rsa.pem -outform PEM -pubout -out rsa_pub.pem
    - scp -r rsa.pem root@$PROD_IP:/root/rsa.pem
    - scp -r rsa_pub.pem root@$PROD_IP:/root/rsa_pub.pem
    - scp -r rsa.pem root@$PROD_IP_2:/root/rsa.pem
    - scp -r rsa_pub.pem root@$PROD_IP_2:/root/rsa_pub.pem
    - ssh -tt root@$PROD_IP "export
      DOCKER_CLIENT_TIMEOUT=120
      COMPOSE_HTTP_TIMEOUT=120
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      MONGODB_PASSWORD=$MONGODB_PASSWORD
      CI_REGISTRY=$CI_REGISTRY
      CI_REGISTRY_USER=$CI_REGISTRY_USER
      CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD
      ADMIN_MAIL=$ADMIN_MAIL
      ADMIN_PASSWORD=$ADMIN_PASSWORD
      MAIL_ADDRESS=$MAIL_ADDRESS
      MAIL_PASSWORD=$MAIL_PASSWORD
      APP_ORIGIN=$APP_ORIGIN
      MAIL_HOST=$MAIL_HOST &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker stack deploy --with-registry-auth -c docker-compose.yml blicc"

plugins:
  stage: seed
  image: node:12
  only:
    - master
  before_script:
    - *enable_ssh
    - git submodule sync --recursive plugins
    - git submodule update --init --recursive --checkout --force plugins
  script:
    - yarn --cwd 'plugins'
    - yarn --cwd 'plugins' deploy
