version: '3.7'

services:
  db:
    build:
      context: ./db
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 5432:5432
  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379
  mongo:
    build:
      context: ./mongo
      args:
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    restart: always
  rabbitmq:
    build: ./rabbitmq
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - 15672:15672
      - 5672:5672
  api:
    build: ./api
    restart: always
    volumes:
      - ./certs:/root/certs
      - ./api/src:/root/src
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NODE_ENV=${NODE_ENV}
    ports:
      - 80:80
  delivery:
    build: ./delivery
    restart: always
    volumes:
      - ./certs:/root/certs
      - ./delivery/cmd:/root/cmd
      - ./delivery/pkg:/root/pkg
      - ./delivery/docs:/root/docs
      - ./delivery/public:/root/public
    depends_on:
      - mongo
      - mock-api
    environment:
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - APP_ORIGIN=${APP_ORIGIN}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 8080:8080
  app:
    build: ./app
    restart: always
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    depends_on:
      - api
      - delivery
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:3000
  mock-api:
    build: ./mock-api
    restart: always
    volumes:
      - ./mock-api/src:/root/src
    ports:
      - 9090:9090
