version: '3'

services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    command:
      - --api.debug=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.exposedByDefault=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`monitor.blicc.org`)
    networks:
      - web
  db:
    image: registry.thiloilg.com/repo/blicc/db:latest
    container_name: db
    restart: always
    networks:
      - internal
  api:
    image: registry.thiloilg.com/repo/blicc/api:latest
    container_name: api
    ports:
      - 80:80
    volumes:
      - /root/rsa.pem:/root/certs/rsa.pem
      - /root/rsa_pub.pem:/root/certs/rsa_pub.pem
    restart: always
    depends_on:
      - db
    environment:
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
    labels:
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.rule=Host(`api.blicc.org`)
    networks:
      - internal
      - web
  app:
    image: registry.thiloilg.com/repo/blicc/app:latest
    container_name: app
    restart: always
    depends_on:
      - api
      - db
    labels:
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.rule=Host(`blicc.org`,`www.blicc.org`)
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false
