version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/acme.json:/root/acme.json
    ports:
      - 80:80
      - 443:443
    command:
      - --api=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.secure.acme.httpchallenge=true
      - --certificatesresolvers.secure.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.secure.acme.email=${MAIL_ADDRESS}
      - --certificatesresolvers.secure.acme.storage=/root/acme.json
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`monitor.testing-stage.org`)
      - traefik.http.routers.traefik.tls.certresolver=secure
      - traefik.http.routers.detour.rule=hostregexp(`{host:[a-z-.]+}`)
      - traefik.http.routers.detour.entrypoints=web
      - traefik.http.routers.detour.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
  db:
    image: registry.thiloilg.com/repo/blicc/db-testing-stage:latest
    restart: always
    labels:
      - traefik.enable=false
  redis:
    image: registry.thiloilg.com/repo/blicc/redis-testing-stage:latest
    restart: always
    labels:
      - traefik.enable=false
  api:
    image: registry.thiloilg.com/repo/blicc/api-testing-stage:latest
    volumes:
      - /root/rsa.pem:/root/certs/rsa.pem
      - /root/rsa_pub.pem:/root/certs/rsa_pub.pem
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    labels:
      - traefik.http.routers.api.rule=Host(`api.testing-stage.org`)
      - traefik.http.routers.api.tls.certresolver=secure
  mock-api:
    image: registry.thiloilg.com/repo/blicc/mock-api-testing-stage:latest
    restart: always
    ports:
      - 9090:9090
    labels:
      - traefik.http.routers.mock-api.rule=Host(`mock.testing-stage.org`)
      - traefik.http.routers.mock-api.tls.certresolver=secure
