version: '3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - 80:80
      - 443:443
    command:
      - --api=true
      - --providers.docker
      - --configFile=/root/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`monitor.blicc.org`)
  db:
    image: registry.thiloilg.com/repo/blicc/db:latest
    restart: always
    labels:
      - traefik.enable=false
  api:
    image: registry.thiloilg.com/repo/blicc/api:latest
    volumes:
      - /root/rsa.pem:/root/certs/rsa.pem
      - /root/rsa_pub.pem:/root/certs/rsa_pub.pem
    restart: always
    depends_on:
      - db
    environment:
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
    labels:
      - traefik.http.routers.api.rule=Host(`api.blicc.org`)
  app:
    image: registry.thiloilg.com/repo/blicc/app:latest
    restart: always
    depends_on:
      - api
      - db
    labels:
      - traefik.http.routers.app.rule=Host(`blicc.org`,`www.blicc.org`)
