version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/traefik.toml:/traefik.toml
      - /root/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - traefik.frontend.rule=Host:monitor.blicc.org
      - traefik.port=8080
    networks:
      - web
  db:
    image: registry.thiloilg.com/repo/blicc/db:latest
    container_name: db
    restart: always
    networks:
      - internal
  api:
    image: registry.thiloilg.com/repo/blicc/api:latest
    container_name: api
    volumes:
      - /root/rsa.pem:/root/certs/rsa.pem
      - /root/rsa_pub.pem:/root/certs/rsa_pub.pem
    restart: always
    depends_on:
      - db
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.blicc.org
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
  app:
    image: registry.thiloilg.com/repo/blicc/app:latest
    container_name: app
    restart: always
    depends_on:
      - api
      - db
    labels:
      - traefik.backend=app
      - traefik.frontend.rule=Host:blicc.org,www.blicc.org
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false
