version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      # - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/traefik.yml:/etc/traefik/traefik.yml
      # - /root/acme.json:/acme.json
    labels:
      - traefik.http.routers.reverse-proxy.rule=Host(`monitor.blicc.org`)
    networks:
      - web
  db:
    image: registry.thiloilg.com/repo/blicc/db:latest
    container_name: db
    restart: always
    networks:
      - internal
  api:
    image: registry.thiloilg.com/repo/blicc/api:latest
    container_name: api
    volumes:
      - /root/rsa.pem:/root/certs/rsa.pem
      - /root/rsa_pub.pem:/root/certs/rsa_pub.pem
    restart: always
    depends_on:
      - db
    environment:
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
    labels:
      - traefik.http.routers.api.rule=Host(`api.blicc.org`)
    networks:
      - internal
      - web
  app:
    image: registry.thiloilg.com/repo/blicc/app:latest
    container_name: app
    restart: always
    depends_on:
      - api
      - db
    labels:
      - traefik.http.routers.app.rule=Host(`blicc.org`,`www.blicc.org`)
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false
