logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
      [entryPoints.dashboard.auth]
        [entryPoints.dashboard.auth.basic]
          users = ["name:hash"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[acme]
email = "email"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "blicc.org"
  sans = ["monitor.blicc.org", "api.blicc.org"]

[docker]
domain = "blicc.org"
watch = true
network = "web"
