entryPoints:
  web:
    address: ':80'

  web-secure:
    address: ':443'

certificatesResolvers:
  sample:
    acme:
      email: example@emai.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
