FROM postgres:11-alpine

ENV POSTGRES_DB=db
ENV POSTGRES_USER=api
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# docker build --no-cache --build-arg POSTGRES_PASSWORD=your_password -t db .
# docker run --rm -p 127.0.0.1:5432:5432 db:latest
